[package]
name = "bp35c0-example"
version = "0.1.0"
edition = "2021"

[dependencies]
bp35c0 = { path = ".." }

anyhow = "1.0"
hex = "0.4.3"
serialport = "4.3"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
